branches:
  only:
    - master
    - /^[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/

version: "0.0.1.{build}"

environment:
  GITHUB_TOKEN:
    secure: MeZRb+x5xfxO5jH93yXs5Tl9MDmH48nmpMF/i5ouAV/frSSonzqDUZmYg8oMMMI8
  APPVEYOR_API_TOKEN:
    secure: eXiEH+/7OgWrbLNGD3aeMGOCsUN5MqXxgRMYci+rCMw=

  matrix:

    # EXPECTED_PYTHON_* are set to the version installed on AppVeyor
    # See https://www.appveyor.com/docs/windows-images-software/#python

    # Visual Studio (Python 2 & 3, 32 & 64 bit)
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON_DIR: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 2.7.15
      EXPECTED_PYTHON_ARCH: 32
      # Test "windows/install-*.ps1" scripts only once
      WINDOWS_ADDON_TESTS: 1

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON_DIR: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 2.7.15
      EXPECTED_PYTHON_ARCH: 64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON_DIR: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 3.5.4
      EXPECTED_PYTHON_ARCH: 32

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON_DIR: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 3.5.4
      EXPECTED_PYTHON_ARCH: 64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON_DIR: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 3.7.2
      EXPECTED_PYTHON_ARCH: 32

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      PYTHON_DIR: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 3.7.2
      EXPECTED_PYTHON_ARCH: 64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON_DIR: "C:\\Python38"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "32"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 3.8.0a2
      EXPECTED_PYTHON_ARCH: 32

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON_DIR: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"
      BLOCK: "0"
      # Used for testing
      EXPECTED_PYTHON_VERSION: 3.8.0a2
      EXPECTED_PYTHON_ARCH: 64

cache:
  - C:\\cmake-3.6.2
  - C:\\Downloads

install:
  - ps: |
      if ($env:PYTHON_VERSION -eq "3.8.x") {
        $pythonVersion = "3.8"
        $pythonArch = "$env:PYTHON_ARCH"
        Invoke-Expression "windows\install-python.ps1"
      }
  - ps: appveyor/rolling-build.ps1
  - python -m pip install scikit-ci==0.15.0
  - python -m ci install

build_script:
  - python -m ci build

test_script:
  - python -m ci test

after_test:
  - python -m ci after_test

on_finish:
  - ps: appveyor/enable-worker-remote-access.ps1 -check_for_block

artifacts:
  - path: dist\*

matrix:
  fast_finish: false

shallow_clone: false
